### PR TITLE
Adds ability to use Mysql database or custom file path storage.

### PR DESCRIPTION
**Pull request by ctwillie**
This PR adds the ability to use a mysql database or an absolute path to a custom file as storage. It will require a new major release as the required PHP version was bumped to 7.3. There is a ton more I want to do, but I figured I would start here.

This would solve the issue [here](https://github.com/Alymosul/exponent-server-sdk-php/issues/69).

There is a couple ```@todo```'s I've added also. Wanted to discuss the expected behavior first.

This will also require changes to the README, but wanted to see if you intended to merge.

### CODE REVIEW

**Comment by Alymosul** [comment]
Hey 👋  Thank you for the amazing work! I'll review the PR on the weekend :)

**Comment by ctwillie** [comment]
@Alymosul 
Ok, cool. There are a couple of "rules" around theses changes that will need to be added to the readme. I will make those changes if you plan to merge. Feel free to reach out when you are reviewing to discuss anything. I will respond in a timely manner.

**Comment by Alymosul** [comment]
I don't get why did you close the PR I haven't had enough time to look into it on the weekend. Let me know if you still want me to reopen and review this PR :)

**Comment by ctwillie** [comment]
@Alymosul
No hard feelings man. I totally get you have been busy.

But, the issues I addressed in the PR was causing strange behavior in our production app. So, I took the time to do the PR, then decided to create my own after waiting.

I've since deleted the fork, but if you still wanted to merge these contributions, let me know and I can re-fork and submit again. I'm just not sure if GitHub lets you merge if the fork doesn't exist anymore.

**Comment by Alymosul** [comment]
I don't have any problems with you creating your own but I see this PR will benefit the package that's why I asked you if you still want me to review and merge it let me know :)

**Comment by ctwillie** [comment]
I agree. If you think it adds benefit to the users of this package, I say definitely reopen. I just didn't know if GitHub lets you reopen a closed PR if the fork has been deleted.

**Comment by Alymosul** [comment]
Ahh! no It won't you will need to submit another PR

**Comment by ctwillie** [comment]
@Alymosul  Luckily, I still have a local copy. So I'll fork again and re-submit the PR!

**Pull request closed without merging**
