### PR TITLE
Multiple tokens per interest

### PR DESCRIPTION
**Pull request by patrickkivits**
Allow the retrieved result of the repository to be an **array**, string or null and handle this result accordingly to create an correct array of tokens.

### CODE REVIEW

**Comment by patrickkivits** [comment]
This pull request accommodates https://github.com/Alymosul/laravel-exponent-push-notifications/pull/12 to support multiple tokens per user using the database driver.

**Comment by Alymosul** [comment]
I think you have to add the saving of multiple tokens to the file driver also.

**Comment by patrickkivits** [comment]
It should handle both single and multiple tokens just fine, see:

- Single token: https://github.com/Alymosul/exponent-server-sdk-php/pull/15/files#diff-54fb5e48fac43f3404c29fc29a47b5deR85

- Multiple tokens: https://github.com/Alymosul/exponent-server-sdk-php/pull/15/files#diff-54fb5e48fac43f3404c29fc29a47b5deR89

But ill see if i can also make the file driver support multiple tokens as well.

**Comment by Alymosul** [comment]
Currently, The file driver overwrites the tokens for the same subscribers keys (identifiers)... Therefore i feel that it won't be comfortable to have one driver adds new tokens to the same subscriber and the other one overwrites any new token for the same subcribers.

Thank you for your contribution :)

**Comment by patrickkivits** [comment]
I understand, therefore i am trying to make the file driver support multiple tokens per subscriber as well.

I hope to add this to this pull request fairly soon :)

**Comment by patrickkivits** [comment]
Here is multiple token support for the file driver aswell: https://github.com/Alymosul/exponent-server-sdk-php/pull/15/commits/ad278e6e367ad28fb96352e28ec10bcc549eaa02

This is also backwards compatible with the old tokens.json file using single tokens as a string value. It will convert any existing key with a single token into an array with the additional token pushed to that array.

So, here in steps the following format:

1. Legacy tokens.json format:
`{"App.User.1":"ExponentPushToken[111111111111111111]"}`

2. New tokens.json format:
`{"App.User.1":["ExponentPushToken[111111111111111111]"]}`

2. New tokens.json format with multiple tokens:
`{"App.User.1":["ExponentPushToken[111111111111111111]","ExponentPushToken[111111111111111112]"]}`

**Review by Alymosul — APPROVED** [review]

**Comment by Alymosul** [comment]
That was fast! Thank you :)

**Pull request merged**
