### PR TITLE
Add documentation for 'store' and 'forget' methods

### PR DESCRIPTION
**Pull request by AleksandarSavic95**
Each method should be described in detail, so that other developers and contributors can use them easily.
I had difficulties while realising what is being done in these methods, so good documentation can help a lot.

### CODE REVIEW

**Review by Alymosul — CHANGES_REQUESTED** [review]
I'm against these additional doc lines. They don't add value but more noise, you should avoid comments as much as possible if we need to make it more readable we should go first to re evaluate the method names and see if we can extract some logic behind an expressive method name... However, the store method is missing type hints that could be added there. Feel free to add the type hints, but if please open a new PR if you're gonna extract some logic to methods.

**Comment by AleksandarSavic95** [comment]
Type hints are a good thing to add, but they won't help in clarifying what the methods do. `store` and `foget` should deffinitely be refactored to be more readable and maintainable. I won't make a pull request just to add type-hints, but I hope someone will have time to rewrite the methods.
I thought documentation is a good thing to have, since all major libraries do, no matter how complex the methods are. Still, it's Your decision :)
Thank You for being so responsive!

**Comment by Alymosul** [comment]
Yeah I agree they can be refactored to make it more readable. But, regarding the docBlocks themselves it's following PSR-2 though these additional sentences on the RHS of the variables or return types should instead be reflected by the code.

**Comment by AleksandarSavic95** [comment]
> Yeah I agree they can be refactored to make it more readable. But, regarding the docBlocks themselves it's following PSR-2 though these additional sentences on the RHS of the variables or return types should instead be reflected by the code.

Please check the docBlock example below the list in the 'variable types' section of [PSR-2 Coding Style Guide Additions](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#variable-types) for information on parameter descriptions.

**Pull request closed without merging**
