### PR TITLE
Throw exception when response is not an array

### LINKED ISSUE #36: TypeError: Argument 1 passed to ExponentPhpSDK\Expo::failedCompletely() must be of the type array
We had a type error from this library, I'm pretty sure that is it due to an error from Expo API, maybe when it doesn't respond or respond an error.

Stacktrace of the error:

```
TypeError: Argument 1 passed to ExponentPhpSDK\Expo::failedCompletely() must be of the type array, null given, called in /app/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php on line 113
#18 vendor/alymosul/exponent-server-sdk-php/lib/Expo.php(128): failedCompletely
#17 vendor/alymosul/exponent-server-sdk-php/lib/Expo.php(113): notify
#16 [project's code …]
#1 vendor/symfony/console/Application.php(145): run
#0 bin/console(39): null
```

Line that trigger the error: https://github.com/Alymosul/exponent-server-sdk-php/blob/4c618200c6cd14e15d0918b317f7f956790ef0dc/lib/Expo.php#L113

Code:

```
$response = $this->executeCurl($ch);

// If the notification failed completely, throw an exception with the details
if (!$debug && $this->failedCompletely($response, $interests)) {
    throw ExpoException::failedCompletelyException($response);
}
```

If `$response` is not an array, calling `$this->failedCompletely($response, $interests)` will fail because the first argument must be an array.

We can replicate the bug by changing value of `$response`: `$response = null;`. Then try to send a notification and you will have the same error.

### PR DESCRIPTION
**Pull request by alexisLefebvre**
Fixes #36

### CODE REVIEW

**Comment by Alymosul** [comment]
I don't think we need to throw an exception, already the `failedCompletely()` is type hinted, therefore already a fatal type error will be thrown. Can you please elaborate on your point of view?

**Comment by Alymosul** [comment]
I don't think we need to throw a special exception for that! The `failedCompletely()` is already type hinted so a fatal TypeError will be thrown. Can you elaborate why we need to throw a special exception?

**Comment by alexisLefebvre** [comment]
Please see #36, if `$response` is `null`, `failedCompletely()` and `failedCompletelyException()` can't work because they expect an array.

So what should we do in this case? Throw a simple `Exception` with a message?

**Comment by alexisLefebvre** [comment]
My first idea was to put the call in a `try {} catch {}` block but the exception from the type hint wasn't caught. I think that the expected behaviour from PHP: we can catch an thrown exception but not an issue with type hint.

**Comment by Alymosul** [comment]
I'd say that inside `executeCurl()` you can do that check on the expected return and if it's not an array you throw `UnexpectedResponseException`

**Comment by alexisLefebvre** [comment]
@Alymosul Thanks, I followed your advice and updated the code.

**Review by Alymosul — APPROVED** [review]
Thanks for your contribution!

**Comment by alexisLefebvre** [comment]
Thanks!

**Comment by alexisLefebvre** [comment]
Could you please publish a new release?

**Comment by Alymosul** [comment]
I'm planning on releasing the next version once i'm done with implementing tests, you can use --dev for now

**Comment by alexisLefebvre** [comment]
Yes, I used this in my `composer.json` : `"alymosul/exponent-server-sdk-php": "dev-master as 1.1.3",`.

`composer validate` throw a warning but no error so it's OK for now.

**Pull request merged**
