### PR TITLE
README: Explain channelName

### PR DESCRIPTION
**Pull request by alexisLefebvre**
See #29

### CODE REVIEW

**Comment by alexisLefebvre** [comment]
Is there a limitation on the format of `$channelName`? Does it accept spaces? Etc.

**Review by Alymosul — CHANGES_REQUESTED** [review]
I think here it would be clearer to add the channelName approach under a section of its own, because we have 2 approaches for registering the tokens. 

Approach 1: We can deal with our notifications channels as `Recipients` and we're creating a `Channel/Recipient`, therefore we're storing the token in a channelName refers to that Recipient's unique identifier.

Approach 2: We can deal with it as `Channels` as `Events` where we can have multiple Recipient in that channel/event.

> Is there a limitation on the format of `$channelName`? Does it accept spaces? Etc.

No spaces or special characters. Alphanumeric characters only!

**Review by williamdes — APPROVED** [review]

**Comment by DannyFeliz** [comment]
Any update on this?

**Comment by alexisLefebvre** [comment]
I somehow deleted the branch of this PR, I'm closing, please see #500

> I think here it would be clearer to add the channelName approach under a section of its own, because we have 2 approaches for registering the tokens.

Thanks!

> > Is there a limitation on the format of `$channelName`? Does it accept spaces? Etc.
> 
> No spaces or special characters. Alphanumeric characters only!

Is `-` a special character? They use it in the documentation: https://docs.expo.io/versions/latest/guides/notification-channels/#send-channel-notification-with-expo-api-service

**Pull request closed without merging**
